/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import java.util.Map;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

import Controller.Examen_Controller;
import util.IDManager;

/**
 *
 * @author josem
 */
public class Desicion_From extends javax.swing.JFrame {

    /**
     * Creates new form Decicion_From
     */
    public Desicion_From() {
        Examen_Controller controller = new Examen_Controller();
        initComponents();

        Map<String, Object> permisos = controller.presentarExamen(IDManager.getInstance().getIdUsuario());
        LabelPruebasRestantes.setText("Pruebas restantes: " + (5-(Integer)permisos.get("puedePresentarPrueba")));
        LabelFinalesRestantes.setText("Finales restantes: "+ (2-(Integer)permisos.get("puedePresentarFinal")));

        
        setLocationRelativeTo(null); 
        LabelNombre.setText(IDManager.getInstance().getNombre_usuario());
        setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        
        addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent windowEvent) {
                regresarADesicionForm();
            }
        });
    }
    private void regresarADesicionForm() {
        Login_Form login = new Login_Form();
        login.setVisible(true);
        this.dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        RadioButtonOpcion1 = new javax.swing.JRadioButton();
        RadioButtonOpcion2 = new javax.swing.JRadioButton();
        RadioButtonOpcion3 = new javax.swing.JRadioButton();
        ButtonSeleccionar = new javax.swing.JButton();
        LabelNombre = new javax.swing.JLabel();
        LabelPruebasRestantes = new javax.swing.JLabel();
        LabelFinalesRestantes = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        buttonGroup1.add(RadioButtonOpcion1);
        RadioButtonOpcion1.setText("Examen Prueba");

        buttonGroup1.add(RadioButtonOpcion2);
        RadioButtonOpcion2.setText("Examen Final");

        buttonGroup1.add(RadioButtonOpcion3);
        RadioButtonOpcion3.setText("Dashbord");

        ButtonSeleccionar.setText("Seleccionar");
        ButtonSeleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSeleccionarActionPerformed(evt);
            }
        });

        LabelNombre.setText("jLabel1");
        

        LabelPruebasRestantes.setText("Pruebas restantes: --");

        LabelFinalesRestantes.setText("Finales restantes: --");


        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ButtonSeleccionar, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(RadioButtonOpcion1, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                        .addComponent(RadioButtonOpcion2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(RadioButtonOpcion3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(LabelNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(LabelPruebasRestantes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(LabelFinalesRestantes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        ))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(LabelNombre)
                .addGap(38, 38, 38)
                .addComponent(LabelPruebasRestantes)
                .addGap(5, 5, 5)
                .addComponent(LabelFinalesRestantes)
                .addGap(20, 20, 20)
                .addComponent(RadioButtonOpcion1)
                .addGap(18, 18, 18)
                .addComponent(RadioButtonOpcion2)
                .addGap(18, 18, 18)
                .addComponent(RadioButtonOpcion3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(ButtonSeleccionar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonSeleccionarActionPerformed(java.awt.event.ActionEvent evt) {
    int tipo = -1;
    Examen_Controller controller = new Examen_Controller();
    if (RadioButtonOpcion1.isSelected()) {
        tipo = 1; // Examen de prueba
    } else if (RadioButtonOpcion2.isSelected()) {
        tipo = 2; // Examen final
    } else if (RadioButtonOpcion3.isSelected()) {
        tipo = 3; // Dashboard
    }
    
    if(tipo == -1) {
        JOptionPane.showMessageDialog(this, "Seleccione una opción", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }
    
    if(tipo == 1 || tipo == 2) {
        Map<String, Object> permisos = controller.presentarExamen(IDManager.getInstance().getIdUsuario()); 
        
        if(tipo == 1 && !((Integer) permisos.get("puedePresentarPrueba") < 5)) {
            JOptionPane.showMessageDialog(this, 
                "Ya has alcanzado el limite de 5 examenes de prueba", 
                "limite alcanzado", 
                JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        if(tipo == 2 && !((Integer) permisos.get("puedePresentarFinal")< 2)) {
            JOptionPane.showMessageDialog(this, 
                "Ya has alcanzado el limite de 2 examenes finales", 
                "limite alcanzado", 
                JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        Examen_Form examen = new Examen_Form(tipo);
        examen.setVisible(true);
        this.dispose();
    }
    else if(tipo == 3) {
        VentanaConGrafica dash = new VentanaConGrafica();
        dash.setVisible(true);
        this.dispose();
    }
}//GEN-LAST:event_ButtonSeleccionarActionPerformed


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Desicion_From.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Desicion_From.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Desicion_From.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Desicion_From.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Desicion_From().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonSeleccionar;
    private javax.swing.JLabel LabelNombre;
    private javax.swing.JRadioButton RadioButtonOpcion1;
    private javax.swing.JRadioButton RadioButtonOpcion2;
    private javax.swing.JRadioButton RadioButtonOpcion3;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel LabelPruebasRestantes;
    private javax.swing.JLabel LabelFinalesRestantes;
    // End of variables declaration//GEN-END:variables
}
