package Vista;

import java.awt.Color;
import javax.swing.ImageIcon;
import javax.swing.JPanel;

import Controller.Register_Controller;
import assets.Enum.ImagenRuta;
import util.IDManager;

/**
 *
 * @author rodry
 */
public class Login_Form extends javax.swing.JPanel {

    MainApp mainApp;
    public Login_Form(MainApp mainApp) {
        initComponents();
        setPreferredSize(new java.awt.Dimension(800, 550));
        this.mainApp = mainApp;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {

        bg = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        emailTxt = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        passwordTxt = new javax.swing.JPasswordField();
        loginBtn = new javax.swing.JButton();
        registerLbl = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Roboto SemiBold", 2, 18)); // NOI18N
        jLabel3.setIcon(new ImageIcon(ImagenRuta.RESIZED.getRuta()));
        jLabel3.setText("  Facultad de Sistemas");
        bg.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 260, 80));

        jLabel4.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        jLabel4.setText("INICIAR SESIÓN");
        bg.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 300, -1));

        jLabel6.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        jLabel6.setText("Correo");
        bg.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, -1, -1));

        emailTxt.setFont(new java.awt.Font("Roboto Thin", 3, 12)); // NOI18N
        emailTxt.setForeground(new java.awt.Color(204, 204, 204));
        emailTxt.setText("Ingrese su correo electrónico");
        emailTxt.setBorder(null);
        emailTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                emailTxtMousePressed(evt);
            }
        });
        bg.add(emailTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, 370, 20));
        emailTxt.getAccessibleContext().setAccessibleName("");

        jSeparator1.setForeground(new java.awt.Color(102, 102, 102));
        bg.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, 370, 10));

        jLabel7.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        jLabel7.setText("Contraseña");
        bg.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, -1, -1));

        jSeparator2.setForeground(new java.awt.Color(102, 102, 102));
        bg.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 350, 370, 10));

        passwordTxt.setForeground(new java.awt.Color(204, 204, 204));
        passwordTxt.setText("********");
        passwordTxt.setBorder(null);
        passwordTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                passwordTxtMousePressed(evt);
            }
        });
        bg.add(passwordTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 330, 370, -1));

        loginBtn.setBackground(new java.awt.Color(188, 4, 51));
        loginBtn.setFont(new java.awt.Font("Roboto Condensed", 1, 12)); // NOI18N
        loginBtn.setForeground(new java.awt.Color(255, 255, 255));
        loginBtn.setText("Ingresar");
        loginBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        loginBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginBtnMouseClicked(evt);
            }
        });
        bg.add(loginBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 390, 100, 30));

        registerLbl.setFont(new java.awt.Font("Roboto Medium", 2, 12)); // NOI18N
        registerLbl.setText("Registrate ahora");
        registerLbl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        registerLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registerLblMouseClicked(evt);
            }
        });
        bg.add(registerLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 460, 90, -1));

        jPanel1.setBackground(new java.awt.Color(65, 71, 68));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new ImageIcon(ImagenRuta.LOGO_UADEC.getRuta()));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(182, Short.MAX_VALUE))
        );

        bg.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 0, 290, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }

    private void emailTxtMousePressed(java.awt.event.MouseEvent evt) {
        if(emailTxt.getText().equals("Ingrese su correo electrónico")) {
            emailTxt.setText("");
            emailTxt.setForeground(Color.black);
        }
        if(String.valueOf(passwordTxt.getPassword()).isEmpty()) {
            passwordTxt.setText("********");
            passwordTxt.setForeground(Color.gray);
        }
    }

    private void passwordTxtMousePressed(java.awt.event.MouseEvent evt) {
        if(String.valueOf(passwordTxt.getPassword()).equals("********")) {
            passwordTxt.setText("");
            passwordTxt.setForeground(Color.black);
        }
        if(emailTxt.getText().isEmpty()) {
            emailTxt.setText("Ingrese su correo electrónico");
            emailTxt.setForeground(Color.gray);
        }
    }

    private void loginBtnMouseClicked(java.awt.event.MouseEvent evt) {
        Register_Controller controller = new Register_Controller();
        if(emailTxt.getText().isEmpty()|| String.valueOf(passwordTxt.getPassword()).isEmpty() || emailTxt.getText().equals("Ingrese su correo electrónico") || String.valueOf(passwordTxt.getPassword()).equals("********")) {
            javax.swing.JOptionPane.showMessageDialog(this, "Por favor, complete todos los campos.");
            return;
        }

        String a = controller.authenticateUser(emailTxt.getText(), new String(passwordTxt.getPassword()));
        if (a != null) {
            
            mainApp.addPanel(new Desicion_From(mainApp), "Desicion");
            mainApp.showPanel("Desicion");
            
        }
    }

    private void registerLblMouseClicked(java.awt.event.MouseEvent evt) {
        
        mainApp.showPanel("Registrar");

        
    }

    // Variables declaration - do not modify
    private javax.swing.JPanel bg;
    private javax.swing.JTextField emailTxt;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JButton loginBtn;
    private javax.swing.JPasswordField passwordTxt;
    private javax.swing.JLabel registerLbl;
    // End of variables declaration
}